-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activision
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_email_activated boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activision_employees
(
    activision_employee_id integer NOT NULL,
    employee_id integer NOT NULL,
    PRIMARY KEY (activision_employee_id)
);

CREATE TABLE public.activision_employers
(
    activision_employer_id integer NOT NULL,
    employer_id integer NOT NULL,
    staff_id integer NOT NULL,
    is_activated_by_staff boolean NOT NULL,
    PRIMARY KEY (activision_employer_id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    employee_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    national_id character varying NOT NULL,
    birth_year date NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name character varying NOT NULL,
    web_site character varying NOT NULL,
    phone_number character varying NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "position" character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_position_id integer NOT NULL,
    description character varying(500) NOT NULL,
    city_id integer NOT NULL,
    max_salary integer,
    min_salary integer,
    open_positions integer NOT NULL,
    latest_apply_time date NOT NULL,
    employer_id integer NOT NULL,
    is_active boolean NOT NULL,
    created_time date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.staffs
(
    staff_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    PRIMARY KEY (staff_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activision_employees
    ADD FOREIGN KEY (activision_employee_id)
    REFERENCES public.activision (id)
    NOT VALID;


ALTER TABLE public.activision_employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.activision_employers
    ADD FOREIGN KEY (activision_employer_id)
    REFERENCES public.activision (id)
    NOT VALID;


ALTER TABLE public.activision_employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.activision_employers
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.staffs (staff_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.staffs
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.users (id)
    NOT VALID;

END;