-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activisions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    activision_code character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cvs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    photo character varying,
    github_link character varying,
    linkedin_link character varying,
    description character varying,
    created_date date NOT NULL,
    is_active boolean NOT NULL,
    latest_update_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.educations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    school_name character varying NOT NULL,
    field character varying NOT NULL,
    begin_date date NOT NULL,
    finish_date date,
    created_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    employee_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    national_id character varying NOT NULL,
    birth_year date NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name character varying NOT NULL,
    web_site character varying NOT NULL,
    phone_number character varying NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.favorites
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    job_id integer NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.favorites
    IS 'Favorite Jobs';

CREATE TABLE public.foreign_languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    language_name character varying NOT NULL,
    created_date date NOT NULL,
    language_level integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_experiences
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    workplace_name character varying NOT NULL,
    job_position_id integer NOT NULL,
    begin_date date NOT NULL,
    finish_date date,
    created_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "position" character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_position_id integer NOT NULL,
    description character varying(500) NOT NULL,
    city_id integer NOT NULL,
    max_salary integer,
    min_salary integer,
    open_positions integer NOT NULL,
    latest_apply_time date NOT NULL,
    employer_id integer NOT NULL,
    is_active boolean NOT NULL,
    created_time date NOT NULL,
    work_time_id integer NOT NULL,
    work_place_id integer NOT NULL,
    is_validated boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.staffs
(
    staff_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    PRIMARY KEY (staff_id)
);

CREATE TABLE public.technologies_and_programming_languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    technology_or_programming_language character varying NOT NULL,
    created_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_places
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_times
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activisions
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.cvs
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.educations
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.favorites
    ADD FOREIGN KEY (job_id)
    REFERENCES public.jobs (id)
    NOT VALID;


ALTER TABLE public.favorites
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.foreign_languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.job_experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.job_experiences
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (work_place_id)
    REFERENCES public.work_places (id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY (work_time_id)
    REFERENCES public.work_times (id)
    NOT VALID;


ALTER TABLE public.staffs
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.technologies_and_programming_languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;

END;